### ISSUE TITLE
file problem

### ISSUE THREAD

**Issue by claudiaann1** [webermarcolivier/xlsxpandasformatter#1]
Im interested in using this package, but I notice your two files xlsxpandasformatter.py and xlsxpandasformatter_example.py are identical, and neither contains the the FormatedWorksheet function.  Am I missing something?

**Comment by webermarcolivier** [comment]
Thank you for pointing this out. Some files got swapped during the repository creation. I updated the file xlsxpandasformatter.py.

**Comment by claudiaann1** [comment]
thanks!

Claudia
