### ISSUE TITLE
not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by guarenty** [webermarcolivier/xlsxpandasformatter#10]
I'm always getting the following Error when I call the 'apply_format_table()' function:
`not enough values to unpack (expected 2, got 1)`

In the example given in the README file this Error also occurs on the 'formattedWorksheet.format_cols()' function.

**Comment by dirkesquire** [comment]
I'm getting the exact same error. Not sure how to solve this.


```
formattedWorksheet.format_col(3, colFormat={'font_size': 8, 'align': 'left'})

formattedWorksheet.format_row(4, rowFormat={'bold': True})

formattedWorksheet.apply_format_table()

writer.save()
```

**error:**

`not enough values to unpack (expected 2, got 1)`

**Comment by dirkesquire** [comment]
The error is being thrown in the `def apply_format_table(self)` function in the last line of code:

```
        # Apply format to index cells
        for j in range(self.nIndexLevels):
            formatDic = self.formatTableIndex[i]
            cellFormat = self.workbook.add_format(formatDic)
            self.worksheet.set_column(xl_range(1, j, 1, j), self.indexColWidth[j], cellFormat)
```

The values of the variables are:
```
i = 0
j = 0
xl_range(1, j, 1, j) returns "A2"
self.indexColWidth[j]  None
```

**Comment by dirkesquire** [comment]
Also managed to get a bit more error information:

```
self.indexColWidth[j] is None
True
xl_range(1, j, 1, j)
'A2'
self.worksheet.set_column(xl_range(1, j, 1, j), self.indexColWidth[j], cellFormat)
Traceback (most recent call last):
  File "/Users/dirk/Dirk/MR/Git/mckinneyrogers.scimitar.importer/.venv/lib/python3.9/site-packages/xlsxwriter/worksheet.py", line 132, in column_wrapper
    int(args[0])
ValueError: invalid literal for int() with base 10: 'A2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dirk/Dirk/MR/Git/mckinneyrogers.scimitar.importer/.venv/lib/python3.9/site-packages/xlsxwriter/worksheet.py", line 135, in column_wrapper
    cell_1, cell_2 = [col + '1' for col in args[0].split(':')]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by dirkesquire** [comment]
Seems like xl_range(1, j, 1, j) is returning the wrong notation to be passed into set_column. It is passing a reference in the format 'A2' or 'B2'.

However set_column wants the column reference to either be a single number argument (referring to the column) OR a string in the format: A:A or B:B or C:C.
This is so set_column can do something for that specific column.

I was looking through utility.py to see if you had an existing function that can return in this format, but unfortunately I couldn't see something. For example maybe a new function is needed to that takes a 1 as input and returns 'A:A' as output.

**Comment by guarenty** [comment]
I sinced moved on from that Project. In the End I did not use xlsxpandasformatter, but wrote my own script that applied formats to the xlsx table. Not a fancy one, but it was fine for my needs. 

But anyway, I looked into it again and I think you are right, xl_range is returning the wrong notation to be passed into set_column.

`xlsxpandasformatter.py line 148:`
```
self.worksheet.set_column(xl_range(1, worksheetCol, 1, worksheetCol), colWidth)
```
But can't u just pass on 'worksheetCol' twice without xl_range? Like so:
```
self.worksheet.set_column(worksheetCol, worksheetCol, colWidth)
```
On line 98 it is the same thing.


When I change both the Example from the README.md works for me, but the 'xlsxpandasformatter_example.py' throws me another Error:
```
  File "/Users/guarenty/Desktop/test xlsx formatter/env/lib/python3.9/site-packages/xlsxpandasformatter/xlsxpandasformatter_example.py", line 113, in <module>
    formattedWorksheet.format_pandas_apply(highlight_value_and_sequence_when_value_is_above_threshold, axis=1)
  File "/Users/guarenty/Desktop/test xlsx formatter/env/lib/python3.9/site-packages/xlsxpandasformatter/xlsxpandasformatter.py", line 308, in format_pandas_apply
    if len(formatDf.columns) != len(self.df.columns):
  File "/Users/guarenty/Desktop/test xlsx formatter/env/lib/python3.9/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'columns'
```

Looking into it now.

**Comment by guarenty** [comment]
Okay, it seems to be a Problem with 'xlsxpandasformatter_example.py' line 97 and below. I think it just got updated in the Readme but not in the example file. I will fork now and fix everything mentioned here.

Thanks for your help @dirkesquire :)

**Comment by guarenty** [comment]
See #11
