### ISSUE TITLE
invalid literal for int() with base 10: 'C2'

### ISSUE THREAD

**Issue by tugodxx** [webermarcolivier/xlsxpandasformatter#6]
I execute your example python file ，but has 啊
error ：invalid literal for int() with base 10: 'C2'，
how to solve

XlsxWriter==1.3.7
pandas==1.1.4

**Comment by KeithTt** [comment]
I followed the official guide of `xlsxwriter` https://xlsxwriter.readthedocs.io/third_party.html here, but this project seems not update yet.

The first question is: `How to install this lib?`

**Comment by webermarcolivier** [comment]
Hi @KeithTt , the script has no pip package. The simplest way to use it is just to copy the files into the same directory of your python project, or into a directory that is in the python path.

**Comment by KeithTt** [comment]
Hi @webermarcolivier , I create a PR to add a `setup.py` config. https://github.com/webermarcolivier/xlsxpandasformatter/pull/7
