### ISSUE TITLE
cannot load module

### ISSUE THREAD

**Issue by dafardevloper** [webermarcolivier/xlsxpandasformatter#8]
cannot load module

traceboack
`"<stdin>", line 1, in <module>
ImportError: cannot import name 'FormatedWorksheet' from 'xlsxpandasformatter' (C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\xlsxpandasformatter\__init__.py)`

**Comment by dantriescoding** [comment]
For me I had to use: 
`from xlsxpandasformatter import FormattedWorksheet`

Seems there might be a typo in the readme file ("FormatedWorksheet") which is fixed in the example.py file.

You can also view the available attributes/methods in this module using:
`print(dir(xlsxpandasformatter))`
